version: '3'

services:
  nginx:
    build:
      context: nginx
    networks:
      - node-network
    container_name: nginx
    ports:
      - "8080:80"
    depends_on:
      - app
  app:
    build: 
      context: ./node
      dockerfile: Dockerfile
    networks:
      - node-network
    volumes:
      - ./node:/home/node/app
      - /home/node/app/node_modules
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    container_name: app
    depends_on:
      - db
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - node-network

networks:
  node-network:
    driver: bridge